package com.real.pojo;
// Generated 26 Jan, 2018 10:26:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Areaunits generated by hbm2java
 */
public class Areaunits  implements java.io.Serializable {


     private Integer areaUnitCode;
     private String plotOrLand;
     private String measurementUnit;
     private Integer areaMeasureemntForDecimal;
     private String securityTag;
     private Date modifiedDate;
     private String modifiedId;
     private String entryBranchCode;
     private Date entryDate;
     private String enteredId;
     private Set groupmasters = new HashSet(0);

    public Areaunits() {
    }

	
    public Areaunits(String plotOrLand, String measurementUnit) {
        this.plotOrLand = plotOrLand;
        this.measurementUnit = measurementUnit;
    }
    public Areaunits(String plotOrLand, String measurementUnit, Integer areaMeasureemntForDecimal, String securityTag, Date modifiedDate, String modifiedId, String entryBranchCode, Date entryDate, String enteredId, Set groupmasters) {
       this.plotOrLand = plotOrLand;
       this.measurementUnit = measurementUnit;
       this.areaMeasureemntForDecimal = areaMeasureemntForDecimal;
       this.securityTag = securityTag;
       this.modifiedDate = modifiedDate;
       this.modifiedId = modifiedId;
       this.entryBranchCode = entryBranchCode;
       this.entryDate = entryDate;
       this.enteredId = enteredId;
       this.groupmasters = groupmasters;
    }
   
    public Integer getAreaUnitCode() {
        return this.areaUnitCode;
    }
    
    public void setAreaUnitCode(Integer areaUnitCode) {
        this.areaUnitCode = areaUnitCode;
    }
    public String getPlotOrLand() {
        return this.plotOrLand;
    }
    
    public void setPlotOrLand(String plotOrLand) {
        this.plotOrLand = plotOrLand;
    }
    public String getMeasurementUnit() {
        return this.measurementUnit;
    }
    
    public void setMeasurementUnit(String measurementUnit) {
        this.measurementUnit = measurementUnit;
    }
    public Integer getAreaMeasureemntForDecimal() {
        return this.areaMeasureemntForDecimal;
    }
    
    public void setAreaMeasureemntForDecimal(Integer areaMeasureemntForDecimal) {
        this.areaMeasureemntForDecimal = areaMeasureemntForDecimal;
    }
    public String getSecurityTag() {
        return this.securityTag;
    }
    
    public void setSecurityTag(String securityTag) {
        this.securityTag = securityTag;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getModifiedId() {
        return this.modifiedId;
    }
    
    public void setModifiedId(String modifiedId) {
        this.modifiedId = modifiedId;
    }
    public String getEntryBranchCode() {
        return this.entryBranchCode;
    }
    
    public void setEntryBranchCode(String entryBranchCode) {
        this.entryBranchCode = entryBranchCode;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getEnteredId() {
        return this.enteredId;
    }
    
    public void setEnteredId(String enteredId) {
        this.enteredId = enteredId;
    }
    public Set getGroupmasters() {
        return this.groupmasters;
    }
    
    public void setGroupmasters(Set groupmasters) {
        this.groupmasters = groupmasters;
    }




}


