package com.real.pojo;
// Generated 26 Jan, 2018 10:26:59 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Businesstypes generated by hbm2java
 */
public class Businesstypes  implements java.io.Serializable {


     private Integer id;
     private String typeOfBusiness;
     private String llshare;
     private Integer companyShare;
     private Set groupmasters = new HashSet(0);

    public Businesstypes() {
    }

    public Businesstypes(String typeOfBusiness, String llshare, Integer companyShare, Set groupmasters) {
       this.typeOfBusiness = typeOfBusiness;
       this.llshare = llshare;
       this.companyShare = companyShare;
       this.groupmasters = groupmasters;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTypeOfBusiness() {
        return this.typeOfBusiness;
    }
    
    public void setTypeOfBusiness(String typeOfBusiness) {
        this.typeOfBusiness = typeOfBusiness;
    }
    public String getLlshare() {
        return this.llshare;
    }
    
    public void setLlshare(String llshare) {
        this.llshare = llshare;
    }
    public Integer getCompanyShare() {
        return this.companyShare;
    }
    
    public void setCompanyShare(Integer companyShare) {
        this.companyShare = companyShare;
    }
    public Set getGroupmasters() {
        return this.groupmasters;
    }
    
    public void setGroupmasters(Set groupmasters) {
        this.groupmasters = groupmasters;
    }




}


