package com.real.pojo;
// Generated 26 Jan, 2018 10:26:59 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Extrapricingitems generated by hbm2java
 */
public class Extrapricingitems  implements java.io.Serializable {


     private Integer extraPricingItemId;
     private String extraPricingItemName;
     private Set groupextrapricings = new HashSet(0);

    public Extrapricingitems() {
    }

    public Extrapricingitems(String extraPricingItemName, Set groupextrapricings) {
       this.extraPricingItemName = extraPricingItemName;
       this.groupextrapricings = groupextrapricings;
    }
   
    public Integer getExtraPricingItemId() {
        return this.extraPricingItemId;
    }
    
    public void setExtraPricingItemId(Integer extraPricingItemId) {
        this.extraPricingItemId = extraPricingItemId;
    }
    public String getExtraPricingItemName() {
        return this.extraPricingItemName;
    }
    
    public void setExtraPricingItemName(String extraPricingItemName) {
        this.extraPricingItemName = extraPricingItemName;
    }
    public Set getGroupextrapricings() {
        return this.groupextrapricings;
    }
    
    public void setGroupextrapricings(Set groupextrapricings) {
        this.groupextrapricings = groupextrapricings;
    }




}


