package com.real.pojo;
// Generated 26 Jan, 2018 10:26:59 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Groupinstallments generated by hbm2java
 */
public class Groupinstallments  implements java.io.Serializable {


     private Integer id;
     private Groupmaster groupmaster;
     private Integer installmentNo;
     private Date installmentDueDate;
     private Integer installmentAmount;
     private String installmentAmountOrPercent;
     private Date installmentStartDate;
     private Date installmentEndDate;
     private Date specialInstallmentDueDate;
     private Integer specialInstallmentAmount;
     private String specialInstallmentAmountOrPercent;

    public Groupinstallments() {
    }

	
    public Groupinstallments(Groupmaster groupmaster) {
        this.groupmaster = groupmaster;
    }
    public Groupinstallments(Groupmaster groupmaster, Integer installmentNo, Date installmentDueDate, Integer installmentAmount, String installmentAmountOrPercent, Date installmentStartDate, Date installmentEndDate, Date specialInstallmentDueDate, Integer specialInstallmentAmount, String specialInstallmentAmountOrPercent) {
       this.groupmaster = groupmaster;
       this.installmentNo = installmentNo;
       this.installmentDueDate = installmentDueDate;
       this.installmentAmount = installmentAmount;
       this.installmentAmountOrPercent = installmentAmountOrPercent;
       this.installmentStartDate = installmentStartDate;
       this.installmentEndDate = installmentEndDate;
       this.specialInstallmentDueDate = specialInstallmentDueDate;
       this.specialInstallmentAmount = specialInstallmentAmount;
       this.specialInstallmentAmountOrPercent = specialInstallmentAmountOrPercent;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Groupmaster getGroupmaster() {
        return this.groupmaster;
    }
    
    public void setGroupmaster(Groupmaster groupmaster) {
        this.groupmaster = groupmaster;
    }
    public Integer getInstallmentNo() {
        return this.installmentNo;
    }
    
    public void setInstallmentNo(Integer installmentNo) {
        this.installmentNo = installmentNo;
    }
    public Date getInstallmentDueDate() {
        return this.installmentDueDate;
    }
    
    public void setInstallmentDueDate(Date installmentDueDate) {
        this.installmentDueDate = installmentDueDate;
    }
    public Integer getInstallmentAmount() {
        return this.installmentAmount;
    }
    
    public void setInstallmentAmount(Integer installmentAmount) {
        this.installmentAmount = installmentAmount;
    }
    public String getInstallmentAmountOrPercent() {
        return this.installmentAmountOrPercent;
    }
    
    public void setInstallmentAmountOrPercent(String installmentAmountOrPercent) {
        this.installmentAmountOrPercent = installmentAmountOrPercent;
    }
    public Date getInstallmentStartDate() {
        return this.installmentStartDate;
    }
    
    public void setInstallmentStartDate(Date installmentStartDate) {
        this.installmentStartDate = installmentStartDate;
    }
    public Date getInstallmentEndDate() {
        return this.installmentEndDate;
    }
    
    public void setInstallmentEndDate(Date installmentEndDate) {
        this.installmentEndDate = installmentEndDate;
    }
    public Date getSpecialInstallmentDueDate() {
        return this.specialInstallmentDueDate;
    }
    
    public void setSpecialInstallmentDueDate(Date specialInstallmentDueDate) {
        this.specialInstallmentDueDate = specialInstallmentDueDate;
    }
    public Integer getSpecialInstallmentAmount() {
        return this.specialInstallmentAmount;
    }
    
    public void setSpecialInstallmentAmount(Integer specialInstallmentAmount) {
        this.specialInstallmentAmount = specialInstallmentAmount;
    }
    public String getSpecialInstallmentAmountOrPercent() {
        return this.specialInstallmentAmountOrPercent;
    }
    
    public void setSpecialInstallmentAmountOrPercent(String specialInstallmentAmountOrPercent) {
        this.specialInstallmentAmountOrPercent = specialInstallmentAmountOrPercent;
    }




}


