package com.real.pojo;
// Generated 26 Jan, 2018 10:26:59 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Grouppricing generated by hbm2java
 */
public class Grouppricing  implements java.io.Serializable {


     private Integer id;
     private Groupmaster groupmaster;
     private String scheme;
     private Date schemeStartDate;
     private Date schemeEndDate;
     private Integer ratePerUnit;
     private Integer period;
     private Integer initialAmount;
     private String initialPercentOrAmount;
     private Integer reservationAmount;
     private String reservationPercentOrAmount;
     private Integer emi;
     private Integer specialInstlmentGap;
     private Integer specialInstalmentAmount;
     private Integer lastAmount;
     private Integer totalCost;
     private Integer temp1;
     private Integer temp2;
     private Integer temp3;
     private Integer temp4;
     private Integer temp5;

    public Grouppricing() {
    }

	
    public Grouppricing(Groupmaster groupmaster) {
        this.groupmaster = groupmaster;
    }
    public Grouppricing(Groupmaster groupmaster, String scheme, Date schemeStartDate, Date schemeEndDate, Integer ratePerUnit, Integer period, Integer initialAmount, String initialPercentOrAmount, Integer reservationAmount, String reservationPercentOrAmount, Integer emi, Integer specialInstlmentGap, Integer specialInstalmentAmount, Integer lastAmount, Integer totalCost, Integer temp1, Integer temp2, Integer temp3, Integer temp4, Integer temp5) {
       this.groupmaster = groupmaster;
       this.scheme = scheme;
       this.schemeStartDate = schemeStartDate;
       this.schemeEndDate = schemeEndDate;
       this.ratePerUnit = ratePerUnit;
       this.period = period;
       this.initialAmount = initialAmount;
       this.initialPercentOrAmount = initialPercentOrAmount;
       this.reservationAmount = reservationAmount;
       this.reservationPercentOrAmount = reservationPercentOrAmount;
       this.emi = emi;
       this.specialInstlmentGap = specialInstlmentGap;
       this.specialInstalmentAmount = specialInstalmentAmount;
       this.lastAmount = lastAmount;
       this.totalCost = totalCost;
       this.temp1 = temp1;
       this.temp2 = temp2;
       this.temp3 = temp3;
       this.temp4 = temp4;
       this.temp5 = temp5;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Groupmaster getGroupmaster() {
        return this.groupmaster;
    }
    
    public void setGroupmaster(Groupmaster groupmaster) {
        this.groupmaster = groupmaster;
    }
    public String getScheme() {
        return this.scheme;
    }
    
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }
    public Date getSchemeStartDate() {
        return this.schemeStartDate;
    }
    
    public void setSchemeStartDate(Date schemeStartDate) {
        this.schemeStartDate = schemeStartDate;
    }
    public Date getSchemeEndDate() {
        return this.schemeEndDate;
    }
    
    public void setSchemeEndDate(Date schemeEndDate) {
        this.schemeEndDate = schemeEndDate;
    }
    public Integer getRatePerUnit() {
        return this.ratePerUnit;
    }
    
    public void setRatePerUnit(Integer ratePerUnit) {
        this.ratePerUnit = ratePerUnit;
    }
    public Integer getPeriod() {
        return this.period;
    }
    
    public void setPeriod(Integer period) {
        this.period = period;
    }
    public Integer getInitialAmount() {
        return this.initialAmount;
    }
    
    public void setInitialAmount(Integer initialAmount) {
        this.initialAmount = initialAmount;
    }
    public String getInitialPercentOrAmount() {
        return this.initialPercentOrAmount;
    }
    
    public void setInitialPercentOrAmount(String initialPercentOrAmount) {
        this.initialPercentOrAmount = initialPercentOrAmount;
    }
    public Integer getReservationAmount() {
        return this.reservationAmount;
    }
    
    public void setReservationAmount(Integer reservationAmount) {
        this.reservationAmount = reservationAmount;
    }
    public String getReservationPercentOrAmount() {
        return this.reservationPercentOrAmount;
    }
    
    public void setReservationPercentOrAmount(String reservationPercentOrAmount) {
        this.reservationPercentOrAmount = reservationPercentOrAmount;
    }
    public Integer getEmi() {
        return this.emi;
    }
    
    public void setEmi(Integer emi) {
        this.emi = emi;
    }
    public Integer getSpecialInstlmentGap() {
        return this.specialInstlmentGap;
    }
    
    public void setSpecialInstlmentGap(Integer specialInstlmentGap) {
        this.specialInstlmentGap = specialInstlmentGap;
    }
    public Integer getSpecialInstalmentAmount() {
        return this.specialInstalmentAmount;
    }
    
    public void setSpecialInstalmentAmount(Integer specialInstalmentAmount) {
        this.specialInstalmentAmount = specialInstalmentAmount;
    }
    public Integer getLastAmount() {
        return this.lastAmount;
    }
    
    public void setLastAmount(Integer lastAmount) {
        this.lastAmount = lastAmount;
    }
    public Integer getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(Integer totalCost) {
        this.totalCost = totalCost;
    }
    public Integer getTemp1() {
        return this.temp1;
    }
    
    public void setTemp1(Integer temp1) {
        this.temp1 = temp1;
    }
    public Integer getTemp2() {
        return this.temp2;
    }
    
    public void setTemp2(Integer temp2) {
        this.temp2 = temp2;
    }
    public Integer getTemp3() {
        return this.temp3;
    }
    
    public void setTemp3(Integer temp3) {
        this.temp3 = temp3;
    }
    public Integer getTemp4() {
        return this.temp4;
    }
    
    public void setTemp4(Integer temp4) {
        this.temp4 = temp4;
    }
    public Integer getTemp5() {
        return this.temp5;
    }
    
    public void setTemp5(Integer temp5) {
        this.temp5 = temp5;
    }




}


