package com.real.pojo;
// Generated 26 Jan, 2018 10:26:59 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Groupextrapricing generated by hbm2java
 */
public class Groupextrapricing  implements java.io.Serializable {


     private Integer id;
     private Extrapricingitems extrapricingitems;
     private Groupmaster groupmaster;
     private String scheme;
     private Integer extraPricingPerUnit;
     private Integer extreaPricingLumpsum;
     private Integer extraPricingPercent;
     private Date extraPricingStartDate;
     private Date extraPricingEndDate;

    public Groupextrapricing() {
    }

	
    public Groupextrapricing(Extrapricingitems extrapricingitems, Groupmaster groupmaster) {
        this.extrapricingitems = extrapricingitems;
        this.groupmaster = groupmaster;
    }
    public Groupextrapricing(Extrapricingitems extrapricingitems, Groupmaster groupmaster, String scheme, Integer extraPricingPerUnit, Integer extreaPricingLumpsum, Integer extraPricingPercent, Date extraPricingStartDate, Date extraPricingEndDate) {
       this.extrapricingitems = extrapricingitems;
       this.groupmaster = groupmaster;
       this.scheme = scheme;
       this.extraPricingPerUnit = extraPricingPerUnit;
       this.extreaPricingLumpsum = extreaPricingLumpsum;
       this.extraPricingPercent = extraPricingPercent;
       this.extraPricingStartDate = extraPricingStartDate;
       this.extraPricingEndDate = extraPricingEndDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Extrapricingitems getExtrapricingitems() {
        return this.extrapricingitems;
    }
    
    public void setExtrapricingitems(Extrapricingitems extrapricingitems) {
        this.extrapricingitems = extrapricingitems;
    }
    public Groupmaster getGroupmaster() {
        return this.groupmaster;
    }
    
    public void setGroupmaster(Groupmaster groupmaster) {
        this.groupmaster = groupmaster;
    }
    public String getScheme() {
        return this.scheme;
    }
    
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }
    public Integer getExtraPricingPerUnit() {
        return this.extraPricingPerUnit;
    }
    
    public void setExtraPricingPerUnit(Integer extraPricingPerUnit) {
        this.extraPricingPerUnit = extraPricingPerUnit;
    }
    public Integer getExtreaPricingLumpsum() {
        return this.extreaPricingLumpsum;
    }
    
    public void setExtreaPricingLumpsum(Integer extreaPricingLumpsum) {
        this.extreaPricingLumpsum = extreaPricingLumpsum;
    }
    public Integer getExtraPricingPercent() {
        return this.extraPricingPercent;
    }
    
    public void setExtraPricingPercent(Integer extraPricingPercent) {
        this.extraPricingPercent = extraPricingPercent;
    }
    public Date getExtraPricingStartDate() {
        return this.extraPricingStartDate;
    }
    
    public void setExtraPricingStartDate(Date extraPricingStartDate) {
        this.extraPricingStartDate = extraPricingStartDate;
    }
    public Date getExtraPricingEndDate() {
        return this.extraPricingEndDate;
    }
    
    public void setExtraPricingEndDate(Date extraPricingEndDate) {
        this.extraPricingEndDate = extraPricingEndDate;
    }




}


