package com.real.pojo;
// Generated 26 Jan, 2018 10:26:59 PM by Hibernate Tools 3.6.0



/**
 * Userdetails generated by hbm2java
 */
public class Userdetails  implements java.io.Serializable {


     private Integer sno;
     private Usermaster usermaster;
     private Rolemaster rolemaster;
     private String password;

    public Userdetails() {
    }

    public Userdetails(Usermaster usermaster, Rolemaster rolemaster, String password) {
       this.usermaster = usermaster;
       this.rolemaster = rolemaster;
       this.password = password;
    }
   
    public Integer getSno() {
        return this.sno;
    }
    
    public void setSno(Integer sno) {
        this.sno = sno;
    }
    public Usermaster getUsermaster() {
        return this.usermaster;
    }
    
    public void setUsermaster(Usermaster usermaster) {
        this.usermaster = usermaster;
    }
    public Rolemaster getRolemaster() {
        return this.rolemaster;
    }
    
    public void setRolemaster(Rolemaster rolemaster) {
        this.rolemaster = rolemaster;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


